#!/usr/bin/env sh

cd $(dirname $0)
source $(dirname $0)/config

# Panel 
PW=2880
PH=40
PX=0
PY=0

while :; do
	
	echo "  $(ws)"
         sleep 0.5	
		 
 done | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$ICONFONT1" -p | \
	while read line; do eval "$line"; done &

