#!/usr/bin/env sh

cd $(dirname $0)
source $(dirname $0)/config

# Panel 
PW=2880
PH=40
PX=0
PY=0

while :; do
	echo "$(ws) $(window) %{c}$(current_time) %{r}$(mpd_status) $(backlight_status) $(volume_status) $(wifi_status) $(battery_status) "
    sleep 1	
		 
 done | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT1" -f "$ICONFONT1" -p | \
	while read line; do eval "$line"; done &

