#!/usr/bin/env sh

# Panel 
PW=2880
PH=40
PX=0
PY=0

# Fonts
FONT1="Roboto:size=8"

# Icon Fonts
ICONFONT1="FontAwesome:size=9"

# Base Colors
base00='151515'
base01='202020'
base02='303030'
base03='505050'
base04='b0b0b0'
base05='d0d0d0'
base06='e0e0e0'
base07='f5f5f5'
base08='fb9fb1'
base09='eda987'
base0A='ddb26f'
base0B='acc267'
base0C='12cfc0'
base0D='6fc2ef'
base0E='e1a3ee'
base0F='deaf8f'

# Opacity Setting
alpha="E0"

# Panel 
BG="#$alpha$base00"
FG="#$base06"

# Sub Panels
BG2="#$alpha$base01"
BG3="#$alpha$base02"
FG7="#$base07"

